[package]
name = "scope-lock"
version = "0.2.3"
edition = "2021"
# TODO: elaborate
description = "Safely extend lifetimes"
# TODO: Apache 2.0
license = "MIT"
repository = "https://github.com/zetanumbers/scope-lock"

[dependencies]
parking_lot = { version = "0.12.2", features = ["send_guard"] }
